### ISSUE TITLE
status异常

### ISSUE THREAD

**Issue by nu0l** [winezer0/passive-scan-client-plus#1]
插件面板-返回状态502，转发失败
<img width="1487" alt="image" src="https://user-images.githubusercontent.com/54735907/212010121-36400b03-fa93-4c9b-a1cd-54d569389028.png">
插件面板-Original response
<img width="553" alt="image" src="https://user-images.githubusercontent.com/54735907/212010210-675743de-fd8b-4bd2-9676-67db5031946e.png">
<img width="465" alt="image" src="https://user-images.githubusercontent.com/54735907/212010672-0bbf38a2-8df3-4695-aaaa-1c7fea64df20.png">

日志：
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/54735907/212010343-24a70313-b2c6-4097-81ca-8fba355812ef.png">

*未开启代理*

**Comment by winezer0** [comment]
比较常见的原因是由于xray等接受转发的代理服务器不可达，请先检查代理是否可以正常使用。
也有可能有其他的原因，需要具体进行分析
