### ISSUE TITLE
插件估计不支持新的Burp版本了吗

### ISSUE THREAD

**Issue by UerTangTang** [winezer0/passive-scan-client-plus#2]
![3b422b46cb61aa0ccb8afb40b728d06](https://github.com/winezer0/passive-scan-client-plus/assets/90227169/f87a7f2d-7de3-4044-9d72-91e93bb051d2)
我的burp版本太高了吗？转发不了流量了。Burp版本是2023.12.1

**Comment by winezer0** [comment]
需要抽时间重新编译看看

**Comment by winezer0** [comment]
看了下编译时有jdk17环境的，看看插件输出的日志有没有提示

**Comment by winezer0** [comment]
测试在2023.12.1版本是正常的
