### ISSUE TITLE
burp 版本 20424.2.1 转发多个ip端口没有流量

### ISSUE THREAD

**Issue by qishi717** [winezer0/passive-scan-client-plus#3]
设置单个ip端口可正常流量转发，设置两个及以上就没有流量转发
![image](https://github.com/user-attachments/assets/f7ee1aa8-63d5-486e-9e47-3da3934fae01)
![image](https://github.com/user-attachments/assets/ed49858e-7d5c-475c-92af-7745acf85fb9)

**Comment by winezer0** [comment]
这个目前还没有支持多目标转发
